import {library} from "@fortawesome/fontawesome-svg-core";

import {
    faArrowRight,
    faAxe,
    faCalendar,
    faCalendarDay,
    faCheck,
    faChevronLeft,
    faChevronRight,
    faCircle,
    faClock, faExclamationTriangle,
    faEye,
    faFeatherAlt,
    faFileImage,
    faFolder,
    faImages,
    faMapMarkerAlt,
    faPaperPlane,
    faPencil,
    faPencilAlt,
    faPenFancy,
    faPlus,
    faQuestion,
    faSignOutAlt, faSpinner,
    faStar,
    faTimes,
    faTrashAlt, faUpload,
    faUserCircle,
    faUserFriends
} from "@fortawesome/pro-solid-svg-icons";


library.add(
    faArrowRight,
    faAxe,
    faCalendar,
    faCalendarDay,
    faCheck,
    faChevronLeft,
    faChevronRight,
    faCircle,
    faClock,
    faEye,
    faFeatherAlt,
    faFileImage,
    faFolder,
    faImages,
    faMapMarkerAlt,
    faPaperPlane,
    faPencil,
    faPencilAlt,
    faPenFancy,
    faPlus,
    faQuestion,
    faSignOutAlt,
    faStar,
    faTimes,
    faTrashAlt,
    faUserCircle,
    faUserFriends,
    faUpload,
    faExclamationTriangle,
    faSpinner
);